Test pre-commit

diff --git a/frontend/.husky/pre-commit b/frontend/.husky/pre-commit
--- a/frontend/.husky/pre-commit
+++ b/frontend/.husky/pre-commit
@@ -1,3 +1,14 @@
-#!/bin/bash
-node_modules/.bin/lint-staged
-echo "Pre-commit хук працює!"
+#!/bin/sh
+. "$(dirname "$0")/husky.sh"
+
+echo "Lint-staged command start..."
+
+npx lint-staged
+
+echo "Starting Cypress tests..."
+npx cypress run
+
+if [ $? -ne 0 ]; then
+  echo "Cypress tests failed. Please fix the errors before committing."
+  exit 1
+fi
